seed: 1234
experiment: 0
num_runs: 3
downstream_task: "edge-prediction"
dataset:
  dataset_name: bitcoin-alpha
  multi_label: False
  is_directed: True
  shape: null # Set at runtime
  num_classes: null # Set at runtime
  normalize: True
subgraph:
  num_subgraphs: 3
  delta: 20
  train_ratio: 0.1
  test_ratio: 0.8
  partitioning: random
  prune: False # This should later be fixed
  pruning_th: 30
model:
  num_samples: [5, 10]
  batch: False
  batch_size: 64
  local_epochs: 1
  lr: 0.001
  weight_decay: 0.0005
  dropout: 0.1
  gnn_layer_type: custom-gat
  data_type: f+s
  smodel_type: LanczosLaplace # GNN, DGCN, CentralDGCN, Laplace, LanczosLaplace, SpectralLaplace, SpectralDGCN, LanczosDGCN
  fmodel_type: GNN #, DGCN, same
  iterations: 200
  metric: auc
feature_model:
  gnn_layer_sizes: [256, 128]
  heads: [32, 16]
  DGCN_layer_sizes: [64]
  mlp_layer_sizes: [256]
  DGCN_layers: 2
structure_model:
  GNN_structure_layers_sizes: []
  DGCN_structure_layers_size: [128]
  DGCN_layers: 10
  # structure_type: degree
  # structure_type: GDV
  # structure_type: fedstar
  # structure_type: mp
  structure_type: hop2vec
  # structure_type: node2vec
  num_structural_features: 512
  estimate: False
  num_mp_vectors: 10
  rw_len: 50
  gnn_epochs: 500
  mlp_epochs: 50
spectral:
  spectral_len: 300
  lanczos_iter: 400
  L_type: "rw" # normal rw sym
  method: "arnoldi" # arnoldi lanczos
  regularizer_coef: 0
  matrix: "lap" # adj lap inc
  decompose: "eigh" # svd eigh
  update_mode: update
node2vec:
  epochs: 50
  walk_length: 20
  context_size: 10
  walks_per_node: 10
  lr: 0.01
  batch_size: 128
  num_negative_samples: 1
  p: 1
  q: 1
  show_bar: True
fedsage:
  neighgen_epochs: 40
  neighgen_lr: 0.002
  neighen_feature_gen: [256, 2048]
  num_pred: 5
  latent_dim: 128
  hidden_layer_sizes: [32]
  impaired_train_nodes_ratio: 0.6
  impaired_test_nodes_ratio: 0.2
  hidden_portion: 0.5
  use_inter_connections: False
  a: 1
  b: 1
  c: 1
fedpub:
  epochs: 50
  frac: 1.0
  clsf_mask_one: True
  laye_mask_one: True
  norm_scale: 3
  lr: 0.001
  weight_decay: 0.000001
  n_dims: 128
  agg_norm: exp
  n_proxy: 10
  l1: 0.001
  loc_l2: 0.001
fedgcn:
  num_hops: 2
  iid_beta: 10000
dynamic:
  use_edge_features: False
  model:
    structural:
      input_dimension: null # Set at runtime
      output_dimension: 128
      layer_dimensions: [256]
      attention_heads: [32, 16]
      dropout: 0.1
      residual: False
    temporal:
      input_dimension: 128
      num_attention_layers: 1
      attention_heads: 16
      dropout: 0.5
      num_snapshots: null # Set at runtime
      use_feedforward: True
  loss_fn: BCEWithLogitsLoss
  min_snapshot: 1
  max_snapshot: 12 # UCI has 13 snapshots
  random_walk:
    num: 10
    length: 40
    window_size: 10
  unsupervised:
    neg_sampling:
      size: 10
      weight: 1.0
      retries: 5
      distortion: 0.75
      tempoal_window: -1
    batch_size: 512
    weight_decay: 0.0005
  max_gradient_norm: 1.0
  evaluation:
    eval_freq: 1
    first_epoch: True
    last_epoch: True
    mode: roland
    link_feature_operator: hadamard
    classifier:
      num_epoch: 100
      loss_fn: BCEWithLogitsLoss
      tx:
        fn: null
        lr: 0.001
        moment: 0.0
        weight_decay: 0.0005
        lr_decay_per_worker_epoch: 1.0
        type_decay_per_worker_epoch: geometric
    data:
      num_val: 0.2
      num_test: 0.6
      is_directed: False
      add_negative_train_samples: True
      neg_sampling_ratio: 1
    query:
      num_pos_samples: 1000
      num_neg_samples_per_pos: -1
      num_retries: 5
wandb:
  project: dynamic-fedlap
  name: null
  group: null
  job_type: dynamic-fedlap-edge-prediction
  mode: online
